name: Release Catalog

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Catalog Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Validate catalog.toml
      run: |
        if [ ! -f catalog.toml ]; then
          echo "❌ catalog.toml not found"
          exit 1
        fi

        # Check file size (should be > 0)
        if [ ! -s catalog.toml ]; then
          echo "❌ catalog.toml is empty"
          exit 1
        fi

        echo "✅ catalog.toml validated"
        echo "File size: $(wc -c < catalog.toml) bytes"

    - name: Count services
      id: count_services
      run: |
        # Count service definitions (lines starting with [[services]])
        SERVICE_COUNT=$(grep -c '^\[\[services\]\]' catalog.toml || echo "0")
        echo "SERVICE_COUNT=${SERVICE_COUNT}" >> $GITHUB_OUTPUT
        echo "Found ${SERVICE_COUNT} services in catalog"

    - name: Generate checksums
      run: |
        sha256sum catalog.toml > catalog.toml.sha256
        cat catalog.toml.sha256

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Catalog ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Doku Service Catalog ${{ steps.get_version.outputs.VERSION }}

          This release contains the service catalog with **${{ steps.count_services.outputs.SERVICE_COUNT }} services**.

          ### Installation

          The catalog will be automatically downloaded when you run:
          ```bash
          doku init
          ```

          Or update manually:
          ```bash
          doku catalog update
          ```

          ### Services Included

          Check the full catalog with:
          ```bash
          doku catalog list
          ```

          ### Checksums

          Verify integrity with:
          ```bash
          sha256sum -c catalog.toml.sha256
          ```
        draft: false
        prerelease: false
        files: |
          catalog.toml
          catalog.toml.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Summary
      run: |
        echo "✅ Catalog release ${{ steps.get_version.outputs.VERSION }} created successfully!"
        echo ""
        echo "📦 Services in catalog: ${{ steps.count_services.outputs.SERVICE_COUNT }}"
        echo "🔗 Download URL: https://github.com/dokulabs/doku-catalog/releases/latest/download/catalog.toml"
